#############################################################################
# Makefile for building: 0-100RealQuick.app/Contents/MacOS/0-100RealQuick
# Generated by qmake (3.0) (Qt 5.7.0)
# Project:  0-100RealQuick.pro
# Template: app
# Command: /Users/Richard/Qt/5.7/clang_64/bin/qmake -spec macx-clang CONFIG+=debug CONFIG+=x86_64 CONFIG+=qml_debug -o Makefile 0-100RealQuick.pro
#############################################################################

MAKEFILE      = Makefile

####### Compiler, tools and options

CC            = /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang
CXX           = /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang++
DEFINES       = -DQT_QML_DEBUG -DQT_QUICK_LIB -DQT_MULTIMEDIA_LIB -DQT_GUI_LIB -DQT_QML_LIB -DQT_NETWORK_LIB -DQT_CORE_LIB
CFLAGS        = -pipe -g -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.9.sdk -mmacosx-version-min=10.8 -Wall -W -fPIC $(DEFINES)
CXXFLAGS      = -pipe -stdlib=libc++ -g -std=gnu++11 -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.9.sdk -mmacosx-version-min=10.8 -Wall -W -fPIC $(DEFINES)
INCPATH       = -I. -I../../../Qt/5.7/clang_64/lib/QtQuick.framework/Headers -I../../../Qt/5.7/clang_64/lib/QtMultimedia.framework/Headers -I../../../Qt/5.7/clang_64/lib/QtGui.framework/Headers -I../../../Qt/5.7/clang_64/lib/QtQml.framework/Headers -I../../../Qt/5.7/clang_64/lib/QtNetwork.framework/Headers -I../../../Qt/5.7/clang_64/lib/QtCore.framework/Headers -I. -I/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.9.sdk/System/Library/Frameworks/OpenGL.framework/Headers -I/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.9.sdk/System/Library/Frameworks/AGL.framework/Headers -I../../../Qt/5.7/clang_64/mkspecs/macx-clang -F/Users/Richard/Qt/5.7/clang_64/lib
QMAKE         = /Users/Richard/Qt/5.7/clang_64/bin/qmake
DEL_FILE      = rm -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p
COPY          = cp -f
COPY_FILE     = cp -f
COPY_DIR      = cp -f -R
INSTALL_FILE  = install -m 644 -p
INSTALL_PROGRAM = install -m 755 -p
INSTALL_DIR   = cp -f -R
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
TAR           = tar -cf
COMPRESS      = gzip -9f
DISTNAME      = 0-100RealQuick1.0.0
DISTDIR = /Users/Richard/Documents/qtcpp/0-100RealQuick/.tmp/0-100RealQuick1.0.0
LINK          = /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang++
LFLAGS        = -headerpad_max_install_names -stdlib=libc++ -Wl,-syslibroot,/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.9.sdk -mmacosx-version-min=10.8 -Wl,-rpath,/Users/Richard/Qt/5.7/clang_64/lib
LIBS          = $(SUBLIBS) -F/Users/Richard/Qt/5.7/clang_64/lib -framework QtQuick -framework QtQml -framework QtNetwork -framework QtCore -framework DiskArbitration -framework IOKit -framework QtGui -framework QtMultimedia -framework OpenGL -framework AGL 
AR            = /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ar cq
RANLIB        = /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ranlib -s
SED           = sed
STRIP         = strip

####### Output directory

OBJECTS_DIR   = ./

####### Files

SOURCES       = main.cpp \
		song.cpp \
		player.cpp \
		ituneslist.cpp qrc_0-100RealQuick.cpp \
		moc_song.cpp \
		moc_player.cpp \
		moc_ituneslist.cpp
OBJECTS       = main.o \
		song.o \
		player.o \
		ituneslist.o \
		qrc_0-100RealQuick.o \
		moc_song.o \
		moc_player.o \
		moc_ituneslist.o
DIST          = ../../../Qt/5.7/clang_64/mkspecs/features/spec_pre.prf \
		../../../Qt/5.7/clang_64/mkspecs/qdevice.pri \
		../../../Qt/5.7/clang_64/mkspecs/features/device_config.prf \
		../../../Qt/5.7/clang_64/mkspecs/common/unix.conf \
		../../../Qt/5.7/clang_64/mkspecs/common/mac.conf \
		../../../Qt/5.7/clang_64/mkspecs/common/macx.conf \
		../../../Qt/5.7/clang_64/mkspecs/common/sanitize.conf \
		../../../Qt/5.7/clang_64/mkspecs/common/gcc-base.conf \
		../../../Qt/5.7/clang_64/mkspecs/common/gcc-base-mac.conf \
		../../../Qt/5.7/clang_64/mkspecs/common/clang.conf \
		../../../Qt/5.7/clang_64/mkspecs/common/clang-mac.conf \
		../../../Qt/5.7/clang_64/mkspecs/qconfig.pri \
		../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_3dcore.pri \
		../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_3dcore_private.pri \
		../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_3dextras.pri \
		../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_3dextras_private.pri \
		../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_3dinput.pri \
		../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_3dinput_private.pri \
		../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_3dlogic.pri \
		../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_3dlogic_private.pri \
		../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_3dquick.pri \
		../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_3dquick_private.pri \
		../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_3dquickextras.pri \
		../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_3dquickextras_private.pri \
		../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_3dquickinput.pri \
		../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_3dquickinput_private.pri \
		../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_3dquickrender.pri \
		../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_3dquickrender_private.pri \
		../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_3drender.pri \
		../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_3drender_private.pri \
		../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_bluetooth.pri \
		../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_bluetooth_private.pri \
		../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_bootstrap_private.pri \
		../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_clucene_private.pri \
		../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_concurrent.pri \
		../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_concurrent_private.pri \
		../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_core.pri \
		../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_core_private.pri \
		../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_dbus.pri \
		../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_dbus_private.pri \
		../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_designer.pri \
		../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_designer_private.pri \
		../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_designercomponents_private.pri \
		../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_gamepad.pri \
		../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_gamepad_private.pri \
		../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_gui.pri \
		../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_gui_private.pri \
		../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_help.pri \
		../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_help_private.pri \
		../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_location.pri \
		../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_location_private.pri \
		../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_macextras.pri \
		../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_macextras_private.pri \
		../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_multimedia.pri \
		../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_multimedia_private.pri \
		../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_multimediawidgets.pri \
		../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_multimediawidgets_private.pri \
		../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_network.pri \
		../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_network_private.pri \
		../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_nfc.pri \
		../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_nfc_private.pri \
		../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_opengl.pri \
		../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_opengl_private.pri \
		../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_openglextensions.pri \
		../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_openglextensions_private.pri \
		../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_packetprotocol_private.pri \
		../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_platformsupport_private.pri \
		../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_positioning.pri \
		../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_positioning_private.pri \
		../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_printsupport.pri \
		../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_printsupport_private.pri \
		../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_purchasing.pri \
		../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_purchasing_private.pri \
		../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_qml.pri \
		../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_qml_private.pri \
		../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_qmldebug_private.pri \
		../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_qmldevtools_private.pri \
		../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_qmltest.pri \
		../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_qmltest_private.pri \
		../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_qtmultimediaquicktools_private.pri \
		../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_quick.pri \
		../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_quick_private.pri \
		../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_quickcontrols2.pri \
		../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_quickcontrols2_private.pri \
		../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_quickparticles_private.pri \
		../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_quicktemplates2_private.pri \
		../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_quickwidgets.pri \
		../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_quickwidgets_private.pri \
		../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_script.pri \
		../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_script_private.pri \
		../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_scripttools.pri \
		../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_scripttools_private.pri \
		../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_scxml.pri \
		../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_scxml_private.pri \
		../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_sensors.pri \
		../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_sensors_private.pri \
		../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_serialbus.pri \
		../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_serialbus_private.pri \
		../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_serialport.pri \
		../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_serialport_private.pri \
		../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_sql.pri \
		../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_sql_private.pri \
		../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_svg.pri \
		../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_svg_private.pri \
		../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_testlib.pri \
		../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_testlib_private.pri \
		../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_uiplugin.pri \
		../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_uitools.pri \
		../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_uitools_private.pri \
		../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_webchannel.pri \
		../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_webchannel_private.pri \
		../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_webengine.pri \
		../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_webengine_private.pri \
		../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_webenginecore.pri \
		../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_webenginecore_private.pri \
		../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_webenginecoreheaders_private.pri \
		../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_webenginewidgets.pri \
		../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_webenginewidgets_private.pri \
		../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_websockets.pri \
		../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_websockets_private.pri \
		../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_webview.pri \
		../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_webview_private.pri \
		../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_widgets.pri \
		../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_widgets_private.pri \
		../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_xml.pri \
		../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_xml_private.pri \
		../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_xmlpatterns.pri \
		../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_xmlpatterns_private.pri \
		../../../Qt/5.7/clang_64/mkspecs/features/qt_functions.prf \
		../../../Qt/5.7/clang_64/mkspecs/features/qt_config.prf \
		../../../Qt/5.7/clang_64/mkspecs/macx-clang/qmake.conf \
		../../../Qt/5.7/clang_64/mkspecs/features/spec_post.prf \
		.qmake.stash \
		../../../Qt/5.7/clang_64/mkspecs/features/exclusive_builds.prf \
		../../../Qt/5.7/clang_64/mkspecs/features/default_pre.prf \
		../../../Qt/5.7/clang_64/mkspecs/features/mac/default_pre.prf \
		../../../Qt/5.7/clang_64/mkspecs/features/resolve_config.prf \
		../../../Qt/5.7/clang_64/mkspecs/features/default_post.prf \
		../../../Qt/5.7/clang_64/mkspecs/features/mac/sdk.prf \
		../../../Qt/5.7/clang_64/mkspecs/features/mac/default_post.prf \
		../../../Qt/5.7/clang_64/mkspecs/features/mac/objective_c.prf \
		../../../Qt/5.7/clang_64/mkspecs/features/qml_debug.prf \
		../../../Qt/5.7/clang_64/mkspecs/features/warn_on.prf \
		../../../Qt/5.7/clang_64/mkspecs/features/qt.prf \
		../../../Qt/5.7/clang_64/mkspecs/features/resources.prf \
		../../../Qt/5.7/clang_64/mkspecs/features/moc.prf \
		../../../Qt/5.7/clang_64/mkspecs/features/unix/opengl.prf \
		../../../Qt/5.7/clang_64/mkspecs/features/unix/thread.prf \
		../../../Qt/5.7/clang_64/mkspecs/features/file_copies.prf \
		../../../Qt/5.7/clang_64/mkspecs/features/mac/rez.prf \
		../../../Qt/5.7/clang_64/mkspecs/features/testcase_targets.prf \
		../../../Qt/5.7/clang_64/mkspecs/features/exceptions.prf \
		../../../Qt/5.7/clang_64/mkspecs/features/yacc.prf \
		../../../Qt/5.7/clang_64/mkspecs/features/lex.prf \
		0-100RealQuick.pro song.h \
		player.h \
		ituneslist.h main.cpp \
		song.cpp \
		player.cpp \
		ituneslist.cpp
QMAKE_TARGET  = 0-100RealQuick
DESTDIR       = 
TARGET        = 0-100RealQuick.app/Contents/MacOS/0-100RealQuick


first: all
####### Build rules

$(TARGET):  $(OBJECTS)  
	@test -d 0-100RealQuick.app/Contents/MacOS/ || mkdir -p 0-100RealQuick.app/Contents/MacOS/
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJCOMP) $(LIBS)

Makefile: 0-100RealQuick.pro ../../../Qt/5.7/clang_64/mkspecs/macx-clang/qmake.conf ../../../Qt/5.7/clang_64/mkspecs/features/spec_pre.prf \
		../../../Qt/5.7/clang_64/mkspecs/qdevice.pri \
		../../../Qt/5.7/clang_64/mkspecs/features/device_config.prf \
		../../../Qt/5.7/clang_64/mkspecs/common/unix.conf \
		../../../Qt/5.7/clang_64/mkspecs/common/mac.conf \
		../../../Qt/5.7/clang_64/mkspecs/common/macx.conf \
		../../../Qt/5.7/clang_64/mkspecs/common/sanitize.conf \
		../../../Qt/5.7/clang_64/mkspecs/common/gcc-base.conf \
		../../../Qt/5.7/clang_64/mkspecs/common/gcc-base-mac.conf \
		../../../Qt/5.7/clang_64/mkspecs/common/clang.conf \
		../../../Qt/5.7/clang_64/mkspecs/common/clang-mac.conf \
		../../../Qt/5.7/clang_64/mkspecs/qconfig.pri \
		../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_3dcore.pri \
		../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_3dcore_private.pri \
		../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_3dextras.pri \
		../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_3dextras_private.pri \
		../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_3dinput.pri \
		../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_3dinput_private.pri \
		../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_3dlogic.pri \
		../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_3dlogic_private.pri \
		../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_3dquick.pri \
		../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_3dquick_private.pri \
		../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_3dquickextras.pri \
		../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_3dquickextras_private.pri \
		../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_3dquickinput.pri \
		../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_3dquickinput_private.pri \
		../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_3dquickrender.pri \
		../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_3dquickrender_private.pri \
		../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_3drender.pri \
		../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_3drender_private.pri \
		../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_bluetooth.pri \
		../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_bluetooth_private.pri \
		../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_bootstrap_private.pri \
		../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_clucene_private.pri \
		../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_concurrent.pri \
		../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_concurrent_private.pri \
		../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_core.pri \
		../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_core_private.pri \
		../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_dbus.pri \
		../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_dbus_private.pri \
		../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_designer.pri \
		../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_designer_private.pri \
		../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_designercomponents_private.pri \
		../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_gamepad.pri \
		../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_gamepad_private.pri \
		../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_gui.pri \
		../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_gui_private.pri \
		../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_help.pri \
		../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_help_private.pri \
		../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_location.pri \
		../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_location_private.pri \
		../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_macextras.pri \
		../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_macextras_private.pri \
		../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_multimedia.pri \
		../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_multimedia_private.pri \
		../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_multimediawidgets.pri \
		../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_multimediawidgets_private.pri \
		../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_network.pri \
		../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_network_private.pri \
		../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_nfc.pri \
		../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_nfc_private.pri \
		../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_opengl.pri \
		../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_opengl_private.pri \
		../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_openglextensions.pri \
		../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_openglextensions_private.pri \
		../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_packetprotocol_private.pri \
		../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_platformsupport_private.pri \
		../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_positioning.pri \
		../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_positioning_private.pri \
		../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_printsupport.pri \
		../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_printsupport_private.pri \
		../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_purchasing.pri \
		../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_purchasing_private.pri \
		../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_qml.pri \
		../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_qml_private.pri \
		../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_qmldebug_private.pri \
		../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_qmldevtools_private.pri \
		../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_qmltest.pri \
		../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_qmltest_private.pri \
		../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_qtmultimediaquicktools_private.pri \
		../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_quick.pri \
		../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_quick_private.pri \
		../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_quickcontrols2.pri \
		../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_quickcontrols2_private.pri \
		../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_quickparticles_private.pri \
		../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_quicktemplates2_private.pri \
		../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_quickwidgets.pri \
		../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_quickwidgets_private.pri \
		../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_script.pri \
		../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_script_private.pri \
		../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_scripttools.pri \
		../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_scripttools_private.pri \
		../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_scxml.pri \
		../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_scxml_private.pri \
		../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_sensors.pri \
		../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_sensors_private.pri \
		../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_serialbus.pri \
		../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_serialbus_private.pri \
		../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_serialport.pri \
		../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_serialport_private.pri \
		../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_sql.pri \
		../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_sql_private.pri \
		../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_svg.pri \
		../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_svg_private.pri \
		../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_testlib.pri \
		../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_testlib_private.pri \
		../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_uiplugin.pri \
		../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_uitools.pri \
		../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_uitools_private.pri \
		../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_webchannel.pri \
		../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_webchannel_private.pri \
		../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_webengine.pri \
		../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_webengine_private.pri \
		../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_webenginecore.pri \
		../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_webenginecore_private.pri \
		../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_webenginecoreheaders_private.pri \
		../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_webenginewidgets.pri \
		../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_webenginewidgets_private.pri \
		../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_websockets.pri \
		../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_websockets_private.pri \
		../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_webview.pri \
		../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_webview_private.pri \
		../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_widgets.pri \
		../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_widgets_private.pri \
		../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_xml.pri \
		../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_xml_private.pri \
		../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_xmlpatterns.pri \
		../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_xmlpatterns_private.pri \
		../../../Qt/5.7/clang_64/mkspecs/features/qt_functions.prf \
		../../../Qt/5.7/clang_64/mkspecs/features/qt_config.prf \
		../../../Qt/5.7/clang_64/mkspecs/macx-clang/qmake.conf \
		../../../Qt/5.7/clang_64/mkspecs/features/spec_post.prf \
		.qmake.stash \
		../../../Qt/5.7/clang_64/mkspecs/features/exclusive_builds.prf \
		../../../Qt/5.7/clang_64/mkspecs/features/default_pre.prf \
		../../../Qt/5.7/clang_64/mkspecs/features/mac/default_pre.prf \
		../../../Qt/5.7/clang_64/mkspecs/features/resolve_config.prf \
		../../../Qt/5.7/clang_64/mkspecs/features/default_post.prf \
		../../../Qt/5.7/clang_64/mkspecs/features/mac/sdk.prf \
		../../../Qt/5.7/clang_64/mkspecs/features/mac/default_post.prf \
		../../../Qt/5.7/clang_64/mkspecs/features/mac/objective_c.prf \
		../../../Qt/5.7/clang_64/mkspecs/features/qml_debug.prf \
		../../../Qt/5.7/clang_64/mkspecs/features/warn_on.prf \
		../../../Qt/5.7/clang_64/mkspecs/features/qt.prf \
		../../../Qt/5.7/clang_64/mkspecs/features/resources.prf \
		../../../Qt/5.7/clang_64/mkspecs/features/moc.prf \
		../../../Qt/5.7/clang_64/mkspecs/features/unix/opengl.prf \
		../../../Qt/5.7/clang_64/mkspecs/features/unix/thread.prf \
		../../../Qt/5.7/clang_64/mkspecs/features/file_copies.prf \
		../../../Qt/5.7/clang_64/mkspecs/features/mac/rez.prf \
		../../../Qt/5.7/clang_64/mkspecs/features/testcase_targets.prf \
		../../../Qt/5.7/clang_64/mkspecs/features/exceptions.prf \
		../../../Qt/5.7/clang_64/mkspecs/features/yacc.prf \
		../../../Qt/5.7/clang_64/mkspecs/features/lex.prf \
		0-100RealQuick.pro \
		0-100RealQuick.qrc \
		../../../Qt/5.7/clang_64/lib/QtQuick.framework/QtQuick.prl \
		../../../Qt/5.7/clang_64/lib/QtMultimedia.framework/QtMultimedia.prl \
		../../../Qt/5.7/clang_64/lib/QtGui.framework/QtGui.prl \
		../../../Qt/5.7/clang_64/lib/QtQml.framework/QtQml.prl \
		../../../Qt/5.7/clang_64/lib/QtNetwork.framework/QtNetwork.prl \
		../../../Qt/5.7/clang_64/lib/QtCore.framework/QtCore.prl
	$(QMAKE) -spec macx-clang CONFIG+=debug CONFIG+=x86_64 CONFIG+=qml_debug -o Makefile 0-100RealQuick.pro
../../../Qt/5.7/clang_64/mkspecs/features/spec_pre.prf:
../../../Qt/5.7/clang_64/mkspecs/qdevice.pri:
../../../Qt/5.7/clang_64/mkspecs/features/device_config.prf:
../../../Qt/5.7/clang_64/mkspecs/common/unix.conf:
../../../Qt/5.7/clang_64/mkspecs/common/mac.conf:
../../../Qt/5.7/clang_64/mkspecs/common/macx.conf:
../../../Qt/5.7/clang_64/mkspecs/common/sanitize.conf:
../../../Qt/5.7/clang_64/mkspecs/common/gcc-base.conf:
../../../Qt/5.7/clang_64/mkspecs/common/gcc-base-mac.conf:
../../../Qt/5.7/clang_64/mkspecs/common/clang.conf:
../../../Qt/5.7/clang_64/mkspecs/common/clang-mac.conf:
../../../Qt/5.7/clang_64/mkspecs/qconfig.pri:
../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_3dcore.pri:
../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_3dcore_private.pri:
../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_3dextras.pri:
../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_3dextras_private.pri:
../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_3dinput.pri:
../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_3dinput_private.pri:
../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_3dlogic.pri:
../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_3dlogic_private.pri:
../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_3dquick.pri:
../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_3dquick_private.pri:
../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_3dquickextras.pri:
../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_3dquickextras_private.pri:
../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_3dquickinput.pri:
../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_3dquickinput_private.pri:
../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_3dquickrender.pri:
../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_3dquickrender_private.pri:
../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_3drender.pri:
../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_3drender_private.pri:
../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_bluetooth.pri:
../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_bluetooth_private.pri:
../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_bootstrap_private.pri:
../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_clucene_private.pri:
../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_concurrent.pri:
../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_concurrent_private.pri:
../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_core.pri:
../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_core_private.pri:
../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_dbus.pri:
../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_dbus_private.pri:
../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_designer.pri:
../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_designer_private.pri:
../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_designercomponents_private.pri:
../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_gamepad.pri:
../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_gamepad_private.pri:
../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_gui.pri:
../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_gui_private.pri:
../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_help.pri:
../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_help_private.pri:
../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_location.pri:
../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_location_private.pri:
../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_macextras.pri:
../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_macextras_private.pri:
../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_multimedia.pri:
../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_multimedia_private.pri:
../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_multimediawidgets.pri:
../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_multimediawidgets_private.pri:
../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_network.pri:
../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_network_private.pri:
../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_nfc.pri:
../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_nfc_private.pri:
../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_opengl.pri:
../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_opengl_private.pri:
../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_openglextensions.pri:
../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_openglextensions_private.pri:
../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_packetprotocol_private.pri:
../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_platformsupport_private.pri:
../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_positioning.pri:
../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_positioning_private.pri:
../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_printsupport.pri:
../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_printsupport_private.pri:
../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_purchasing.pri:
../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_purchasing_private.pri:
../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_qml.pri:
../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_qml_private.pri:
../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_qmldebug_private.pri:
../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_qmldevtools_private.pri:
../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_qmltest.pri:
../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_qmltest_private.pri:
../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_qtmultimediaquicktools_private.pri:
../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_quick.pri:
../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_quick_private.pri:
../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_quickcontrols2.pri:
../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_quickcontrols2_private.pri:
../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_quickparticles_private.pri:
../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_quicktemplates2_private.pri:
../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_quickwidgets.pri:
../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_quickwidgets_private.pri:
../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_script.pri:
../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_script_private.pri:
../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_scripttools.pri:
../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_scripttools_private.pri:
../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_scxml.pri:
../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_scxml_private.pri:
../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_sensors.pri:
../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_sensors_private.pri:
../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_serialbus.pri:
../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_serialbus_private.pri:
../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_serialport.pri:
../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_serialport_private.pri:
../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_sql.pri:
../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_sql_private.pri:
../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_svg.pri:
../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_svg_private.pri:
../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_testlib.pri:
../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_testlib_private.pri:
../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_uiplugin.pri:
../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_uitools.pri:
../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_uitools_private.pri:
../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_webchannel.pri:
../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_webchannel_private.pri:
../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_webengine.pri:
../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_webengine_private.pri:
../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_webenginecore.pri:
../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_webenginecore_private.pri:
../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_webenginecoreheaders_private.pri:
../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_webenginewidgets.pri:
../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_webenginewidgets_private.pri:
../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_websockets.pri:
../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_websockets_private.pri:
../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_webview.pri:
../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_webview_private.pri:
../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_widgets.pri:
../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_widgets_private.pri:
../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_xml.pri:
../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_xml_private.pri:
../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_xmlpatterns.pri:
../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_xmlpatterns_private.pri:
../../../Qt/5.7/clang_64/mkspecs/features/qt_functions.prf:
../../../Qt/5.7/clang_64/mkspecs/features/qt_config.prf:
../../../Qt/5.7/clang_64/mkspecs/macx-clang/qmake.conf:
../../../Qt/5.7/clang_64/mkspecs/features/spec_post.prf:
.qmake.stash:
../../../Qt/5.7/clang_64/mkspecs/features/exclusive_builds.prf:
../../../Qt/5.7/clang_64/mkspecs/features/default_pre.prf:
../../../Qt/5.7/clang_64/mkspecs/features/mac/default_pre.prf:
../../../Qt/5.7/clang_64/mkspecs/features/resolve_config.prf:
../../../Qt/5.7/clang_64/mkspecs/features/default_post.prf:
../../../Qt/5.7/clang_64/mkspecs/features/mac/sdk.prf:
../../../Qt/5.7/clang_64/mkspecs/features/mac/default_post.prf:
../../../Qt/5.7/clang_64/mkspecs/features/mac/objective_c.prf:
../../../Qt/5.7/clang_64/mkspecs/features/qml_debug.prf:
../../../Qt/5.7/clang_64/mkspecs/features/warn_on.prf:
../../../Qt/5.7/clang_64/mkspecs/features/qt.prf:
../../../Qt/5.7/clang_64/mkspecs/features/resources.prf:
../../../Qt/5.7/clang_64/mkspecs/features/moc.prf:
../../../Qt/5.7/clang_64/mkspecs/features/unix/opengl.prf:
../../../Qt/5.7/clang_64/mkspecs/features/unix/thread.prf:
../../../Qt/5.7/clang_64/mkspecs/features/file_copies.prf:
../../../Qt/5.7/clang_64/mkspecs/features/mac/rez.prf:
../../../Qt/5.7/clang_64/mkspecs/features/testcase_targets.prf:
../../../Qt/5.7/clang_64/mkspecs/features/exceptions.prf:
../../../Qt/5.7/clang_64/mkspecs/features/yacc.prf:
../../../Qt/5.7/clang_64/mkspecs/features/lex.prf:
0-100RealQuick.pro:
0-100RealQuick.qrc:
../../../Qt/5.7/clang_64/lib/QtQuick.framework/QtQuick.prl:
../../../Qt/5.7/clang_64/lib/QtMultimedia.framework/QtMultimedia.prl:
../../../Qt/5.7/clang_64/lib/QtGui.framework/QtGui.prl:
../../../Qt/5.7/clang_64/lib/QtQml.framework/QtQml.prl:
../../../Qt/5.7/clang_64/lib/QtNetwork.framework/QtNetwork.prl:
../../../Qt/5.7/clang_64/lib/QtCore.framework/QtCore.prl:
qmake: FORCE
	@$(QMAKE) -spec macx-clang CONFIG+=debug CONFIG+=x86_64 CONFIG+=qml_debug -o Makefile 0-100RealQuick.pro

qmake_all: FORCE

0-100RealQuick.app/Contents/PkgInfo: 
	@test -d 0-100RealQuick.app/Contents || mkdir -p 0-100RealQuick.app/Contents
	@$(DEL_FILE) 0-100RealQuick.app/Contents/PkgInfo
	@echo "APPL????" > 0-100RealQuick.app/Contents/PkgInfo
0-100RealQuick.app/Contents/Resources/empty.lproj: 
	@test -d 0-100RealQuick.app/Contents/Resources || mkdir -p 0-100RealQuick.app/Contents/Resources
	@touch 0-100RealQuick.app/Contents/Resources/empty.lproj
	
0-100RealQuick.app/Contents/Info.plist: 
	@test -d 0-100RealQuick.app/Contents || mkdir -p 0-100RealQuick.app/Contents
	@$(DEL_FILE) 0-100RealQuick.app/Contents/Info.plist
	@sed -e "s,@SHORT_VERSION@,1.0,g" -e "s,@FULL_VERSION@,1.0.0,g" -e "s,@TYPEINFO@,????,g" -e "s,@BUNDLEIDENTIFIER@,com.yourcompany.0-100RealQuick,g" -e "s,@ICON@,,g" -e "s,@EXECUTABLE@,0-100RealQuick,g" -e "s,@LIBRARY@,0-100RealQuick,g" -e "s,@TYPEINFO@,????,g" ../../../Qt/5.7/clang_64/mkspecs/macx-clang/Info.plist.app >0-100RealQuick.app/Contents/Info.plist

all: Makefile \
		0-100RealQuick.app/Contents/PkgInfo \
		0-100RealQuick.app/Contents/Resources/empty.lproj \
		0-100RealQuick.app/Contents/Info.plist $(TARGET)

dist: distdir FORCE
	(cd `dirname $(DISTDIR)` && $(TAR) $(DISTNAME).tar $(DISTNAME) && $(COMPRESS) $(DISTNAME).tar) && $(MOVE) `dirname $(DISTDIR)`/$(DISTNAME).tar.gz . && $(DEL_FILE) -r $(DISTDIR)

distdir: FORCE
	@test -d $(DISTDIR) || mkdir -p $(DISTDIR)
	$(COPY_FILE) --parents $(DIST) $(DISTDIR)/
	$(COPY_FILE) --parents 0-100RealQuick.qrc $(DISTDIR)/
	$(COPY_FILE) --parents song.h player.h ituneslist.h $(DISTDIR)/
	$(COPY_FILE) --parents main.cpp song.cpp player.cpp ituneslist.cpp $(DISTDIR)/


clean: compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


distclean: clean 
	-$(DEL_FILE) -r 0-100RealQuick.app
	-$(DEL_FILE) .qmake.stash
	-$(DEL_FILE) Makefile


####### Sub-libraries

mocclean: compiler_moc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_source_make_all

check: first

benchmark: first

compiler_rcc_make_all: qrc_0-100RealQuick.cpp
compiler_rcc_clean:
	-$(DEL_FILE) qrc_0-100RealQuick.cpp
qrc_0-100RealQuick.cpp: 0-100RealQuick.qrc \
		../../../Qt/5.7/clang_64/bin/rcc \
		view.qml \
		Song.qml
	/Users/Richard/Qt/5.7/clang_64/bin/rcc -name 0-100RealQuick 0-100RealQuick.qrc -o qrc_0-100RealQuick.cpp

compiler_moc_header_make_all: moc_song.cpp moc_player.cpp moc_ituneslist.cpp
compiler_moc_header_clean:
	-$(DEL_FILE) moc_song.cpp moc_player.cpp moc_ituneslist.cpp
moc_song.cpp: ../../../Qt/5.7/clang_64/lib/QtCore.framework/Headers/QObject \
		../../../Qt/5.7/clang_64/lib/QtCore.framework/Headers/qobject.h \
		../../../Qt/5.7/clang_64/lib/QtGui.framework/Headers/QColor \
		../../../Qt/5.7/clang_64/lib/QtGui.framework/Headers/qcolor.h \
		song.h \
		../../../Qt/5.7/clang_64/bin/moc
	/Users/Richard/Qt/5.7/clang_64/bin/moc $(DEFINES) -D__APPLE__ -D__GNUC__=4 -D__APPLE_CC__ -I/Users/Richard/Qt/5.7/clang_64/mkspecs/macx-clang -I/Users/Richard/Documents/qtcpp/0-100RealQuick -I/Users/Richard/Qt/5.7/clang_64/lib/QtQuick.framework/Headers -I/Users/Richard/Qt/5.7/clang_64/lib/QtMultimedia.framework/Headers -I/Users/Richard/Qt/5.7/clang_64/lib/QtGui.framework/Headers -I/Users/Richard/Qt/5.7/clang_64/lib/QtQml.framework/Headers -I/Users/Richard/Qt/5.7/clang_64/lib/QtNetwork.framework/Headers -I/Users/Richard/Qt/5.7/clang_64/lib/QtCore.framework/Headers -I/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib/c++/v1 -I/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib/clang/5.1/include -I/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include -I/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.9.sdk/usr/include -I'/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.9.sdk/System/Library/Frameworks (framework directory)' -F/Users/Richard/Qt/5.7/clang_64/lib song.h -o moc_song.cpp

moc_player.cpp: ../../../Qt/5.7/clang_64/lib/QtCore.framework/Headers/QObject \
		../../../Qt/5.7/clang_64/lib/QtCore.framework/Headers/qobject.h \
		../../../Qt/5.7/clang_64/lib/QtMultimedia.framework/Headers/QMediaPlayer \
		../../../Qt/5.7/clang_64/lib/QtMultimedia.framework/Headers/qmediaplayer.h \
		../../../Qt/5.7/clang_64/lib/QtMultimedia.framework/Headers/QMediaPlaylist \
		../../../Qt/5.7/clang_64/lib/QtMultimedia.framework/Headers/qmediaplaylist.h \
		song.h \
		../../../Qt/5.7/clang_64/lib/QtGui.framework/Headers/QColor \
		../../../Qt/5.7/clang_64/lib/QtGui.framework/Headers/qcolor.h \
		player.h \
		../../../Qt/5.7/clang_64/bin/moc
	/Users/Richard/Qt/5.7/clang_64/bin/moc $(DEFINES) -D__APPLE__ -D__GNUC__=4 -D__APPLE_CC__ -I/Users/Richard/Qt/5.7/clang_64/mkspecs/macx-clang -I/Users/Richard/Documents/qtcpp/0-100RealQuick -I/Users/Richard/Qt/5.7/clang_64/lib/QtQuick.framework/Headers -I/Users/Richard/Qt/5.7/clang_64/lib/QtMultimedia.framework/Headers -I/Users/Richard/Qt/5.7/clang_64/lib/QtGui.framework/Headers -I/Users/Richard/Qt/5.7/clang_64/lib/QtQml.framework/Headers -I/Users/Richard/Qt/5.7/clang_64/lib/QtNetwork.framework/Headers -I/Users/Richard/Qt/5.7/clang_64/lib/QtCore.framework/Headers -I/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib/c++/v1 -I/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib/clang/5.1/include -I/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include -I/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.9.sdk/usr/include -I'/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.9.sdk/System/Library/Frameworks (framework directory)' -F/Users/Richard/Qt/5.7/clang_64/lib player.h -o moc_player.cpp

moc_ituneslist.cpp: ../../../Qt/5.7/clang_64/lib/QtCore.framework/Headers/QObject \
		../../../Qt/5.7/clang_64/lib/QtCore.framework/Headers/qobject.h \
		../../../Qt/5.7/clang_64/lib/QtNetwork.framework/Headers/QNetworkAccessManager \
		../../../Qt/5.7/clang_64/lib/QtNetwork.framework/Headers/qnetworkaccessmanager.h \
		../../../Qt/5.7/clang_64/lib/QtCore.framework/Headers/QXmlStreamReader \
		../../../Qt/5.7/clang_64/lib/QtCore.framework/Headers/qxmlstream.h \
		../../../Qt/5.7/clang_64/lib/QtCore.framework/Headers/QXmlStreamAttributes \
		../../../Qt/5.7/clang_64/lib/QtNetwork.framework/Headers/QNetworkReply \
		../../../Qt/5.7/clang_64/lib/QtNetwork.framework/Headers/qnetworkreply.h \
		../../../Qt/5.7/clang_64/lib/QtCore.framework/Headers/QTemporaryFile \
		../../../Qt/5.7/clang_64/lib/QtCore.framework/Headers/qtemporaryfile.h \
		song.h \
		../../../Qt/5.7/clang_64/lib/QtGui.framework/Headers/QColor \
		../../../Qt/5.7/clang_64/lib/QtGui.framework/Headers/qcolor.h \
		player.h \
		../../../Qt/5.7/clang_64/lib/QtMultimedia.framework/Headers/QMediaPlayer \
		../../../Qt/5.7/clang_64/lib/QtMultimedia.framework/Headers/qmediaplayer.h \
		../../../Qt/5.7/clang_64/lib/QtMultimedia.framework/Headers/QMediaPlaylist \
		../../../Qt/5.7/clang_64/lib/QtMultimedia.framework/Headers/qmediaplaylist.h \
		ituneslist.h \
		../../../Qt/5.7/clang_64/bin/moc
	/Users/Richard/Qt/5.7/clang_64/bin/moc $(DEFINES) -D__APPLE__ -D__GNUC__=4 -D__APPLE_CC__ -I/Users/Richard/Qt/5.7/clang_64/mkspecs/macx-clang -I/Users/Richard/Documents/qtcpp/0-100RealQuick -I/Users/Richard/Qt/5.7/clang_64/lib/QtQuick.framework/Headers -I/Users/Richard/Qt/5.7/clang_64/lib/QtMultimedia.framework/Headers -I/Users/Richard/Qt/5.7/clang_64/lib/QtGui.framework/Headers -I/Users/Richard/Qt/5.7/clang_64/lib/QtQml.framework/Headers -I/Users/Richard/Qt/5.7/clang_64/lib/QtNetwork.framework/Headers -I/Users/Richard/Qt/5.7/clang_64/lib/QtCore.framework/Headers -I/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib/c++/v1 -I/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib/clang/5.1/include -I/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include -I/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.9.sdk/usr/include -I'/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.9.sdk/System/Library/Frameworks (framework directory)' -F/Users/Richard/Qt/5.7/clang_64/lib ituneslist.h -o moc_ituneslist.cpp

compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_rez_source_make_all:
compiler_rez_source_clean:
compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: compiler_rcc_clean compiler_moc_header_clean 

####### Compile

main.o: main.cpp ../../../Qt/5.7/clang_64/lib/QtGui.framework/Headers/QGuiApplication \
		../../../Qt/5.7/clang_64/lib/QtGui.framework/Headers/qguiapplication.h \
		../../../Qt/5.7/clang_64/lib/QtQml.framework/Headers/qqmlengine.h \
		../../../Qt/5.7/clang_64/lib/QtQml.framework/Headers/qqmlcontext.h \
		../../../Qt/5.7/clang_64/lib/QtQml.framework/Headers/qqml.h \
		../../../Qt/5.7/clang_64/lib/QtCore.framework/Headers/QObject \
		../../../Qt/5.7/clang_64/lib/QtCore.framework/Headers/qobject.h \
		../../../Qt/5.7/clang_64/lib/QtCore.framework/Headers/QDebug \
		../../../Qt/5.7/clang_64/lib/QtCore.framework/Headers/qdebug.h \
		song.h \
		../../../Qt/5.7/clang_64/lib/QtGui.framework/Headers/QColor \
		../../../Qt/5.7/clang_64/lib/QtGui.framework/Headers/qcolor.h \
		ituneslist.h \
		../../../Qt/5.7/clang_64/lib/QtNetwork.framework/Headers/QNetworkAccessManager \
		../../../Qt/5.7/clang_64/lib/QtNetwork.framework/Headers/qnetworkaccessmanager.h \
		../../../Qt/5.7/clang_64/lib/QtCore.framework/Headers/QXmlStreamReader \
		../../../Qt/5.7/clang_64/lib/QtCore.framework/Headers/qxmlstream.h \
		../../../Qt/5.7/clang_64/lib/QtCore.framework/Headers/QXmlStreamAttributes \
		../../../Qt/5.7/clang_64/lib/QtNetwork.framework/Headers/QNetworkReply \
		../../../Qt/5.7/clang_64/lib/QtNetwork.framework/Headers/qnetworkreply.h \
		../../../Qt/5.7/clang_64/lib/QtCore.framework/Headers/QTemporaryFile \
		../../../Qt/5.7/clang_64/lib/QtCore.framework/Headers/qtemporaryfile.h \
		player.h \
		../../../Qt/5.7/clang_64/lib/QtMultimedia.framework/Headers/QMediaPlayer \
		../../../Qt/5.7/clang_64/lib/QtMultimedia.framework/Headers/qmediaplayer.h \
		../../../Qt/5.7/clang_64/lib/QtMultimedia.framework/Headers/QMediaPlaylist \
		../../../Qt/5.7/clang_64/lib/QtMultimedia.framework/Headers/qmediaplaylist.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o main.o main.cpp

song.o: song.cpp ../../../Qt/5.7/clang_64/lib/QtCore.framework/Headers/QDebug \
		../../../Qt/5.7/clang_64/lib/QtCore.framework/Headers/qdebug.h \
		song.h \
		../../../Qt/5.7/clang_64/lib/QtCore.framework/Headers/QObject \
		../../../Qt/5.7/clang_64/lib/QtCore.framework/Headers/qobject.h \
		../../../Qt/5.7/clang_64/lib/QtGui.framework/Headers/QColor \
		../../../Qt/5.7/clang_64/lib/QtGui.framework/Headers/qcolor.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o song.o song.cpp

player.o: player.cpp player.h \
		../../../Qt/5.7/clang_64/lib/QtCore.framework/Headers/QObject \
		../../../Qt/5.7/clang_64/lib/QtCore.framework/Headers/qobject.h \
		../../../Qt/5.7/clang_64/lib/QtMultimedia.framework/Headers/QMediaPlayer \
		../../../Qt/5.7/clang_64/lib/QtMultimedia.framework/Headers/qmediaplayer.h \
		../../../Qt/5.7/clang_64/lib/QtMultimedia.framework/Headers/QMediaPlaylist \
		../../../Qt/5.7/clang_64/lib/QtMultimedia.framework/Headers/qmediaplaylist.h \
		song.h \
		../../../Qt/5.7/clang_64/lib/QtGui.framework/Headers/QColor \
		../../../Qt/5.7/clang_64/lib/QtGui.framework/Headers/qcolor.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o player.o player.cpp

ituneslist.o: ituneslist.cpp ituneslist.h \
		../../../Qt/5.7/clang_64/lib/QtCore.framework/Headers/QObject \
		../../../Qt/5.7/clang_64/lib/QtCore.framework/Headers/qobject.h \
		../../../Qt/5.7/clang_64/lib/QtNetwork.framework/Headers/QNetworkAccessManager \
		../../../Qt/5.7/clang_64/lib/QtNetwork.framework/Headers/qnetworkaccessmanager.h \
		../../../Qt/5.7/clang_64/lib/QtCore.framework/Headers/QXmlStreamReader \
		../../../Qt/5.7/clang_64/lib/QtCore.framework/Headers/qxmlstream.h \
		../../../Qt/5.7/clang_64/lib/QtCore.framework/Headers/QXmlStreamAttributes \
		../../../Qt/5.7/clang_64/lib/QtNetwork.framework/Headers/QNetworkReply \
		../../../Qt/5.7/clang_64/lib/QtNetwork.framework/Headers/qnetworkreply.h \
		../../../Qt/5.7/clang_64/lib/QtCore.framework/Headers/QTemporaryFile \
		../../../Qt/5.7/clang_64/lib/QtCore.framework/Headers/qtemporaryfile.h \
		song.h \
		../../../Qt/5.7/clang_64/lib/QtGui.framework/Headers/QColor \
		../../../Qt/5.7/clang_64/lib/QtGui.framework/Headers/qcolor.h \
		player.h \
		../../../Qt/5.7/clang_64/lib/QtMultimedia.framework/Headers/QMediaPlayer \
		../../../Qt/5.7/clang_64/lib/QtMultimedia.framework/Headers/qmediaplayer.h \
		../../../Qt/5.7/clang_64/lib/QtMultimedia.framework/Headers/QMediaPlaylist \
		../../../Qt/5.7/clang_64/lib/QtMultimedia.framework/Headers/qmediaplaylist.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o ituneslist.o ituneslist.cpp

qrc_0-100RealQuick.o: qrc_0-100RealQuick.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o qrc_0-100RealQuick.o qrc_0-100RealQuick.cpp

moc_song.o: moc_song.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_song.o moc_song.cpp

moc_player.o: moc_player.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_player.o moc_player.cpp

moc_ituneslist.o: moc_ituneslist.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_ituneslist.o moc_ituneslist.cpp

####### Install

install_target: first FORCE
	@test -d $(INSTALL_ROOT)/opt/0-100RealQuick/bin || mkdir -p $(INSTALL_ROOT)/opt/0-100RealQuick/bin
	$(DEL_FILE) -r $(INSTALL_ROOT)/opt/0-100RealQuick/bin/0-100RealQuick.app
	
	-$(INSTALL_DIR) 0-100RealQuick.app $(INSTALL_ROOT)/opt/0-100RealQuick/bin/0-100RealQuick.app

uninstall_target: FORCE
	-$(DEL_FILE) -r $(INSTALL_ROOT)/opt/0-100RealQuick/bin/0-100RealQuick.app
	-$(DEL_DIR) $(INSTALL_ROOT)/opt/0-100RealQuick/bin/ 


install: install_target  FORCE

uninstall: uninstall_target  FORCE

FORCE:

